services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=PathPrefix(`/`)"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.routers.portfolio.priority=1"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
      - "traefik.http.routers.portfolio.middlewares=security-headers@file"

networks:
  web:
    external: true
